apiVersion: v1
kind: Pod
metadata:
  name: xgcd-debug
  namespace: longweiwangusd
spec:
  containers:
  - name: jupyter-container
    image: continuumio/anaconda3:latest
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: data-storage
      mountPath: /data
    - name: dshm
      mountPath: /dev/shm
    resources:
      requests:
        memory: "16Gi"
        cpu: "4"
      limits:
        memory: "16Gi"
        cpu: "4"
  volumes:
  - name: data-storage
    persistentVolumeClaim:
      claimName: vindr-cxr-pvc
  - name: dshm
    emptyDir:
      medium: Memory
      sizeLimit: "8Gi"
  restartPolicy: Never